# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Справочник по построению многоугольника")
        MainWindow.resize(1000, 800)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0852273 rgba(255, 255, 255, 255), stop:0.869318 rgba(126, 7, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(186, 12, 631, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 24pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setGeometry(QtCore.QRect(50, 90, 341, 551))
        self.verticalWidget.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalWidget)
        self.label_2.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.verticalWidget)
        self.spinBox.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.label_4 = QtWidgets.QLabel(self.verticalWidget)
        self.label_4.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.spinBox_2 = QtWidgets.QSpinBox(self.verticalWidget)
        self.spinBox_2.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout.addWidget(self.spinBox_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalWidget)
        self.label_3.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.verticalWidget)
        self.comboBox.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalWidget)
        self.pushButton.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_3.setGeometry(QtCore.QRect(575, 89, 400, 231))
        self.verticalWidget_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_5.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalWidget_3)
        self.textBrowser.setStyleSheet("font: 18pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.label_6 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_6.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.verticalWidget_3)
        self.textBrowser_2.setStyleSheet("font: 18pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_3.addWidget(self.textBrowser_2)
        self.label_7 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_7.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.verticalWidget_3)
        self.textBrowser_3.setStyleSheet("font: 18pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_3.addWidget(self.textBrowser_3)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(575, 332, 400, 400))
        self.label_8.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Справочник по построению многоугольника"))
        self.label_2.setText(_translate("MainWindow", "Укажите количество сторон:"))
        self.label_4.setText(_translate("MainWindow", "Укажите длину стороны:"))
        self.label_3.setText(_translate("MainWindow", "Выберите цвет:"))
        self.pushButton.setText(_translate("MainWindow", "Выполнить"))
        self.label_5.setText(_translate("MainWindow", "Площадь:"))
        self.label_6.setText(_translate("MainWindow", "Периметр:"))
        self.label_7.setText(_translate("MainWindow", "Внутренний угол:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
