/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test_strncmp.check" instead.
 */

#include <check.h>
#include <string.h>

#include "s21_string.h"

START_TEST(strncpy1) {
  char str[50] = "Hello";
  char str1[50] = "Hello";
  ck_assert_pstr_eq(s21_strncpy(str, "    ", 10), strncpy(str1, "    ", 10));
}
END_TEST

START_TEST(strncpy2) {
  char str[50] = "";
  char str1[50] = "";
  ck_assert_pstr_eq(s21_strncpy(str, "Hello world\n\0", 15),
                    strncpy(str1, "Hello world\n\0", 15));
}
END_TEST

START_TEST(strncpy3) {
  char str[50] = "a\n\0";
  char str1[50] = "a\n\0";
  ck_assert_pstr_eq(s21_strncpy(str, " \n\0", 5), strncpy(str1, " \n\0", 5));
}
END_TEST

START_TEST(strncpy4) {
  char str[50] = "Hel   lo";
  char str1[50] = "Hel   lo";
  ck_assert_pstr_eq(s21_strncpy(str, "a\n\0", 10), strncpy(str1, "a\n\0", 10));
}
END_TEST

START_TEST(strncpy5) {
  char str[50] = "Hello world\n\0";
  char str1[50] = "Hello world\n\0";
  ck_assert_pstr_eq(s21_strncpy(str, "\n\0", 15), strncpy(str1, "\n\0", 15));
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);

  tcase_add_test(tc1_1, strncpy1);
  tcase_add_test(tc1_1, strncpy2);
  tcase_add_test(tc1_1, strncpy3);
  tcase_add_test(tc1_1, strncpy4);
  tcase_add_test(tc1_1, strncpy5);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}